# Generated by Django 5.0.14 on 2025-05-14 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_shopping_cart_products_shopping_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_ID',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='seller_ID',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.seller'),
            preserve_default=False,
        ),
    ]
