# Generated by Django 5.0.14 on 2025-05-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_ID',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
