# Generated by Django 5.0.14 on 2025-05-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_product_customer_seller_shopping_cart_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart',
            name='products',
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='product',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ID',
            field=models.IntegerField(),
        ),
    ]
