# Generated by Django 5.0.14 on 2025-05-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
