# Generated by Django 5.0.14 on 2025-05-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_product_product_id'),
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_ID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, to='blog.product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ID',
            field=models.CharField(max_length=255),
        ),
    ]
